import Link from "next/link";
import { redirect } from "next/navigation";
import { DashboardShell } from "@/components/dashboard/DashboardShell";
import { EventActions } from "@/components/admin/EventActions";
import { requireAdmin } from "@/lib/auth/session";
import { getAdminDb, isFirebaseAdminConfigured } from "@/lib/firebase/admin";
import { eventStatusLabel } from "@/lib/wedding/status";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
export default async function AdminHome() { if (!isFirebaseAdminConfigured()) return <main className="setup-required"><h1>Configura Firebase</h1><p>Completa `.env.local` siguiendo `FIREBASE_SETUP.md` para habilitar el administrador.</p></main>; let user; try { user = await requireAdmin(); } catch { redirect("/admin/login"); } const snapshot = await getAdminDb().collection("events").orderBy("createdAt", "desc").limit(100).get(); const events = snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() })); const counts = { published: events.filter((item) => item.status === "published").length, draft: events.filter((item) => item.status === "draft").length, archived: events.filter((item) => item.status === "archived").length }; return <DashboardShell area="admin" user={user}><header className="dashboard-header"><div><span className="dashboard-eyebrow">Administración</span><h1>Eventos</h1><p>Consulta las invitaciones, controla su publicación y entrega el acceso a cada cliente.</p></div><Link className="button" href="/admin/bodas/nueva">Crear invitación</Link></header><div className="stats-grid"><article><span>Total eventos</span><strong>{events.length}</strong></article><article><span>Publicados</span><strong>{counts.published}</strong></article><article><span>Borradores</span><strong>{counts.draft}</strong></article><article><span>Archivados</span><strong>{counts.archived}</strong></article></div><section className="dashboard-card"><div className="dashboard-card__title"><h2>Eventos recientes</h2></div>{events.length ? <div className="responsive-table"><table><thead><tr><th>Evento</th><th>Enlace</th><th>Estado</th><th>Fecha</th><th>Acciones</th></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td><strong>{event.publicData?.eventTitle || [event.publicData?.couple?.partner1,event.publicData?.couple?.partner2].filter(Boolean).join(" & ") || "Invitación"}</strong></td><td>{event.publicPath || `/eventos/${event.slug}`}</td><td><span className={`status status--${event.status}`}>{eventStatusLabel(event.status)}</span></td><td>{event.publicData?.weddingDate?.iso?.slice(0, 10)}</td><td><EventActions event={{ id: event.id, slug: event.slug, status: event.status, publicPath: event.publicPath }} /></td></tr>)}</tbody></table></div> : <div className="empty-state"><h3>Todavía no hay eventos</h3><p>Los eventos publicados con el comando de activación aparecerán aquí.</p></div>}</section></DashboardShell>; }
