const images = "/images/events/catalina-y-jorge";
export const catalinaJorge = {
  slug: "catalina-y-jorge",
  templateKey: "catalina-jorge-beige-olive",
  eventTitle: "Boda de Catalina y Jorge",
  couple: { partner1: "Catalina Peñuelas", partner2: "Jorge Oronia" },
  displayNames: { partner1: "Catalina", partner2: "Jorge" },
  date: "2027-01-23T20:00:00-07:00",
  timezone: "America/Mazatlan",
  maxCompanions: 0,
  rsvpEnabled: true,
  dateStamp: "23 · 01 · 2027",
  dateDisplay: "Sábado · 23 de enero · 2027",
  calendarDate: "23 de enero de 2027",
  timelineDate: "23 de enero",
  hero: {
    subtitle: "Nuestra boda",
    quote: "Con el amor que nos une y la ilusión de seguir caminando juntos, queremos compartir contigo la alegría de nuestra boda.",
    image: `${images}/image copy 2.png`,
  },
  closingImage: `${images}/image copy.png`,
  ceremony: { enabled: true, name: "Ceremonia en la playa", time: "", address: "", mapsUrl: "", image: `${images}/floral.png` },
  reception: { enabled: true, name: "Mazatlán, Sinaloa", time: "8:00 p. m.", address: "Calle Deportistas, colonia Salvador Allende", mapsUrl: "", image: `${images}/floral.png` },
  gallery: [
    { src: `${images}/image.png`, width: 485, height: 480, alt: "Catalina y Jorge, un recuerdo juntos" },
    { src: `${images}/image copy.png`, width: 480, height: 720, alt: "Retrato de Catalina y Jorge" },
    { src: `${images}/image copy 2.png`, width: 480, height: 720, alt: "Catalina y Jorge abrazados" },
  ],
  dressCode: { title: "Formal elegante", text: "Te invitamos a acompañarnos con un atuendo formal y elegante." },
  gifts: [{ name: "Un detalle con cariño", description: "Si deseas obsequiarnos algo, cualquier detalle será recibido con mucho cariño y gratitud.", type: "text" }],
  contact: {},
  music: { enabled: false, url: "", label: "Nuestra canción" },
  itinerary: [],
  theme: { primary: "#66704b", dark: "#343d2d", champagne: "#d0bb8d", cream: "#f4eddf", ivory: "#fffdf7", rose: "#d1bfa6", sage: "#89916c" },
};
