export const erickErika = {
  slug: "erick-y-erika",
  templateKey: "erick-erika-champagne",
  eventTitle: "Boda de Erick y Erika",
  couple: { partner1: "Erick", partner2: "Erika" },
  date: "2026-11-14T11:00:00-06:00",
  endDate: "2026-11-15T18:00:00-06:00",
  timezone: "America/Mexico_City",
  rsvpDeadline: "2026-11-07T23:59:00-06:00",
  rsvpDeadlineDisplay: "7 de noviembre",
  maxCompanions: 5,
  dateStamp: "14 · 11 · 2026",
  dateDisplay: "Sábado · 14 de noviembre · 2026",
  calendarDate: "14 y 15 de noviembre de 2026",
  timelineDate: "14 de noviembre",
  hero: {
    subtitle: "Nuestra boda",
    quote: "Con la bendición de Dios y de nuestros padres, queremos compartir contigo el día en que uniremos nuestras vidas para siempre.",
    image: "/images/events/erick-erika/foto-4.jpeg",
  },
  thought: [
    "No fue casualidad,\nfue el destino escribiéndonos despacio.\nDos nombres que riman\npara dos almas que encajan.",
    "De todos los caminos,\nelegimos el mismo.\nDe todos los amores,\nelegimos el nuestro.",
    "Porque contigo entendí\nque el amor no se busca,\nse reconoce.",
    "Hoy sellamos con un Sí\nlo que Dios ya había unido\ndesde siempre.",
  ],
  bibleVerse: {
    reference: "Génesis 2:24",
    text: "Por eso el hombre dejará a su padre y a su madre, y se unirá a su mujer, y los dos serán una sola carne.",
  },
  family: {
    groups: [
      { title: "Con la bendición de nuestros padres", names: ["Sr. Sergio Toledo Antonio", "Sra. Raquel González Zacarías", "Sra. Hermelinda Concepción Alcántara Rivera"] },
      { title: "Padrinos de velación", names: ["Benigno Torres Marín", "Gloria Villanueva Pérez"] },
      { title: "Padrinos de vela", names: ["Wilfrido Atanacio Cayetano", "María del Carmen Antonio Vázquez"] },
    ],
  },
  ceremony: {
    name: "Parroquia de Nuestra Señora de la Candelaria",
    time: "11:00 a. m.",
    address: "Parroquia de Nuestra Señora de la Candelaria",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Parroquia+de+Nuestra+Se%C3%B1ora+de+la+Candelaria",
    image: "/images/events/erick-erika/foto-2.jpeg",
  },
  reception: {
    name: "Salón San Isidro Labrador",
    time: "1:00 p. m.",
    address: "Boda civil, baile y brindis",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Salon+San+Isidro+Labrador",
    image: "/images/events/erick-erika/foto-7.jpeg",
  },
  itinerary: [
    { time: "11:00", title: "Ceremonia religiosa", description: "Parroquia de Nuestra Señora de la Candelaria", icon: "heart" },
    { time: "13:00", title: "Boda civil", description: "Salón San Isidro Labrador", icon: "rings" },
    { time: "Después", title: "Baile y brindis", description: "Celebremos juntos nuestra unión", icon: "glass" },
  ],
  nextDayEvent: {
    title: "Tradicional Lavada de Olla",
    date: "Domingo 15 de noviembre de 2026",
    time: "2:00 p. m.",
    place: "Salón San Isidro Labrador",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Salon+San+Isidro+Labrador",
  },
  gallery: [
    { src: "/images/events/erick-erika/foto-1.jpeg", alt: "Erick y Erika compartiendo un momento juntos" },
    { src: "/images/events/erick-erika/foto-2.jpeg", alt: "Retrato de Erick y Erika" },
    { src: "/images/events/erick-erika/foto-3.jpeg", alt: "Erick y Erika celebrando su historia" },
    { src: "/images/events/erick-erika/foto-4.jpeg", alt: "Erick y Erika en blanco y negro" },
    { src: "/images/events/erick-erika/foto-5.jpeg", alt: "Un recuerdo especial de Erick y Erika" },
    { src: "/images/events/erick-erika/foto-6.jpeg", alt: "Erick y Erika juntos" },
    { src: "/images/events/erick-erika/foto-7.jpeg", alt: "La historia de amor de Erick y Erika" },
    { src: "/images/events/erick-erika/foto-8.jpeg", alt: "Erick y Erika, una vida juntos" },
  ],
  contact: { phone: "", whatsapp: "" },
  music: {
    enabled: true,
    url: "/audio/erick-erika-cancion.mpeg",
    label: "Nuestra canción",
  },
  theme: {
    primary: "#8b674d",
    dark: "#3f2c24",
    champagne: "#c5a476",
    cream: "#eee0cf",
    ivory: "#fffaf2",
    rose: "#b59072",
    sage: "#786354",
  },
};
