export const keylaXv = {
  slug: "xv-keyla",
  templateKey: "keyla-xv-disco",
  eventTitle: "XV años de Keyla",
  couple: { partner1: "Keyla", partner2: "Mis XV" },
  date: "2026-12-05T18:00:00-06:00",
  endDate: "2026-12-06T01:00:00-06:00",
  timezone: "America/Mexico_City",
  maxCompanions: 0,
  hero: {
    subtitle: "Mis XV años",
    quote: "Una noche para brillar, bailar y celebrar juntos.",
    image: "/images/events/keyla-xv/foto-2.webp",
  },
  ceremony: {
    enabled: true,
    name: "San Francisco de Almoloyan",
    time: "18:00",
    address: "Esquina Maclovio Herrera y Av. de los Maestros s/n, Colima, Col.",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=San+Francisco+de+Almoloyan+Maclovio+Herrera+Avenida+de+los+Maestros+Colima",
    image: "/images/events/keyla-xv/foto-4.webp",
  },
  reception: {
    enabled: true,
    name: "Terraza Potrillos",
    time: "20:00",
    address: "Lib. Pte. Colima–Manzanillo km 1.2, Prados del Sur, Colima, Col.",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Terraza+Potrillos+Libramiento+Poniente+Colima+Manzanillo+km+1.2",
    image: "/images/events/keyla-xv/foto-5.webp",
  },
  itinerary: [
    { time: "18:00", title: "Misa", description: "San Francisco de Almoloyan", icon: "heart" },
    { time: "20:00", title: "Recepción", description: "Terraza Potrillos", icon: "sparkles" },
    { time: "21:00", title: "Cena", description: "Terraza Potrillos", icon: "glass" },
    { time: "22:00", title: "Baile", description: "Celebremos juntos", icon: "music" },
  ],
  dressCode: {
    title: "Formal / elegante",
    text: "El color azul está reservado para la quinceañera y el beige para las damas.",
  },
  gallery: [
    { src: "/images/events/keyla-xv/foto-1.webp", alt: "Keyla celebrando sus quince años frente al mar" },
    { src: "/images/events/keyla-xv/foto-3.webp", alt: "Keyla en la playa junto al número quince" },
    { src: "/images/events/keyla-xv/foto-6.jpg", alt: "Pastel disco con la fecha de los XV años de Keyla" },
    { src: "/images/events/keyla-xv/keyla-7.jpg", alt: "Keyla leyendo el anuncio de sus próximos XV años" },
  ],
  gifts: [],
  importantInfo: ["Estacionamiento por calle A y calle 2, Zona Industrial, Colima, Col."],
  contact: { phone: "3122002067", whatsapp: "https://wa.me/523122002067" },
  music: { enabled: true, url: "/audio/keyla-dancing-queen.mp3", label: "Dancing Queen" },
  theme: { primary: "#6f86b6", dark: "#090a0d", champagne: "#d7c3a7", cream: "#eceef4", ivory: "#f9f8f5", rose: "#dce0e8", sage: "#6f86b6" },
};
