export const krystelXv = {
  slug: "xv-krystel",
  templateKey: "krystel-xv-muted-aqua-champagne-gold",
  eventTitle: "XV años de Krystel",
  couple: { partner1: "Krystel", partner2: "Mis XV" },
  date: "2026-12-27T17:00:00-06:00",
  endDate: "2026-12-28T02:00:00-06:00",
  timezone: "America/Chihuahua",
  rsvpDeadline: "2026-12-20T23:59:00-06:00",
  maxCompanions: 3,
  hero: {
    subtitle: "Mis XV años",
    quote: "Hay momentos inolvidables que se guardan para siempre en el corazón. Me hará muy feliz compartir contigo esta noche tan especial.",
    image: "/images/events/krystel-xv/hero-floral.png",
  },
  ceremony: {
    enabled: true,
    name: "Iglesia de Santa María Magdalena",
    time: "5:00 p. m.",
    address: "La Magdalena, Balleza, Chih.",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Santa+Maria+Magdalena+Balleza+Chihuahua",
    image: "/images/events/krystel-xv/ceremony-decoration.png",
  },
  reception: {
    enabled: true,
    name: "Auditorio Municipal",
    time: "6:30 p. m.",
    address: "Balleza, Chihuahua",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Auditorio+Municipal+Balleza+Chihuahua",
    image: "/images/events/krystel-xv/reception-decoration.png",
  },
  itinerary: [
    { time: "17:00", displayTime: "5:00", title: "Ceremonia religiosa", description: "Iglesia de Santa María Magdalena", icon: "heart" },
    { time: "18:30", displayTime: "6:30", title: "Recepción", description: "Auditorio Municipal, Balleza, Chih.", icon: "glass" },
    { time: "18:30", displayTime: "6:30", title: "Cena", description: "6:30 p. m. – 8:30 p. m.", icon: "sparkles" },
    { time: "20:30", displayTime: "8:30", title: "Brindis", description: "", icon: "glass" },
    { time: "20:45", displayTime: "8:45", title: "Vals", description: "", icon: "heart" },
    { time: "21:00", displayTime: "9:00", title: "Baile", description: "9:00 p. m. – 2:00 a. m.", icon: "music" },
  ],
  family: { parents: ["Luis Carlos Hernández P.", "Élida Bustillos S."], godparents: [] },
  dressCode: { title: "Aqua, champagne y dorado reservados", text: "Agradecemos elegir otros tonos para tu vestimenta." },
  gifts: [{ name: "Regalo o sobre", description: "Tu presencia es mi mejor regalo. Si deseas tener un detalle conmigo, puedes elegir un regalo o un sobre.", url: "", type: "cash" }],
  gallery: [],
  contact: { phone: "6491180778", whatsapp: "https://wa.me/526491180778" },
  music: { enabled: true, url: "/audio/krystel.mp3", label: "Mi canción" },
  theme: { primary: "#5fa6aa", dark: "#3f7378", champagne: "#d8c3a5", cream: "#edf6f5", ivory: "#fffdf8", rose: "#dfc98d", sage: "#8fc4c2" },
};
