export const margaritaMateo = {
  slug: "margarita-y-mateo",
  templateKey: "margarita-mateo-azul-plata",
  eventTitle: "Boda de Margarita y Mateo",
  couple: { partner1: "Margarita Laureano Torres", partner2: "Mateo Aquino García" },
  date: "2026-12-19T10:00:00-06:00",
  endDate: "2026-12-20T00:00:00-06:00",
  timezone: "America/Mexico_City",
  rsvpDeadline: "2026-12-12T23:59:00-06:00",
  rsvpDeadlineDisplay: "12 de diciembre",
  maxCompanions: 5,
  dateStamp: "19 · 12 · 2026",
  dateDisplay: "Sábado · 19 de diciembre · 2026",
  timelineDate: "19 de diciembre",
  calendarDate: "19 de diciembre de 2026",
  hero: {
    subtitle: "Nuestra boda",
    quote: "Hay momentos que se vuelven inolvidables cuando se comparten con las personas que queremos. Nos encantará celebrar este día contigo.",
    image: "/images/events/margarita-mateo/foto-1.webp",
  },
  ceremony: {
    name: "Iglesia San Juan Bautista",
    time: "10:00 a. m.",
    address: "Iglesia San Juan Bautista, Coscomatepec, Veracruz",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Iglesia+San+Juan+Bautista+Coscomatepec+Veracruz",
    image: "/images/events/margarita-mateo/foto-2.webp",
  },
  reception: {
    name: "Salón Campestre El Terreno",
    time: "3:00 p. m.",
    address: "Salón Campestre El Terreno, Coscomatepec, Veracruz",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Salon+Campestre+El+Terreno+Coscomatepec+Veracruz",
    image: "/images/events/margarita-mateo/foto-3.webp",
  },
  gallery: [
    { src: "/images/events/margarita-mateo/foto-1.webp", alt: "Margarita y Mateo compartiendo un momento especial" },
    { src: "/images/events/margarita-mateo/foto-2.webp", alt: "Retrato de Margarita y Mateo" },
    { src: "/images/events/margarita-mateo/foto-3.webp", alt: "Margarita y Mateo celebrando su historia" },
    { src: "/images/events/margarita-mateo/foto-4.webp", alt: "Margarita y Mateo juntos" },
    { src: "/images/events/margarita-mateo/foto-5.webp", alt: "Un recuerdo de Margarita y Mateo" },
    { src: "/images/events/margarita-mateo/foto-6.webp", alt: "Margarita y Mateo compartiendo su felicidad" },
  ],
  family: {
    brideParents: ["Gabriela Laureano Torres", "José Pedro Laureano Torres †"],
    groomParents: ["Natividad García Dorantes", "José Aquino Lucas †"],
    godparents: ["Gabriela Reyes Guzmán", "José Emilio López Rivera"],
    memorial: "Con amor, recordamos a José Pedro Laureano Torres y José Aquino Lucas, quienes nos acompañan desde el cielo.",
  },
  dressCode: {
    title: "Formal · Casual",
    text: "Elige un atuendo formal-casual con el que te sientas cómodo para celebrar con nosotros.",
  },
  gifts: [{
    name: "Lluvia de sobres",
    description: "Tu presencia es nuestro mejor regalo. Si deseas tener un detalle con nosotros, durante la recepción habrá lluvia de sobres.",
    url: "",
    type: "cash",
  }],
  contact: {
    phone: "5579989340",
    whatsapp: "https://wa.me/525579989340",
  },
  music: {
    enabled: true,
    url: "/audio/margarita-mateo-perfect-espanol.mp3",
    label: "Perfect · versión en español",
  },
  itinerary: [
    { time: "10:00", title: "Ceremonia", description: "Iglesia San Juan Bautista", icon: "heart" },
    { time: "15:00", title: "Recepción", description: "Salón Campestre El Terreno", icon: "glass" },
  ],
  theme: { primary: "#123b8f", dark: "#0b1d43", champagne: "#b9c2cf", cream: "#e8ecf3", ivory: "#fffdfa", rose: "#688bd1", sage: "#71858b" },
};
