export const saraBlase = {
  slug: "sara-y-blase",
  templateKey: "sara-blase-terracota",
  eventTitle: "Boda de Sara y Blase",
  couple: { partner1: "Sara", partner2: "Blase" },
  date: "2026-11-07T16:00:00-06:00",
  endDate: "2026-11-08T00:00:00-06:00",
  timezone: "America/Mexico_City",
  rsvpDeadline: "2026-10-31T23:59:00-06:00",
  maxCompanions: 5,
  hero: {
    subtitle: "Nuestra boda",
    quote: "Hay momentos que se vuelven inolvidables cuando se comparten con las personas que queremos. Nos encantará celebrar este día contigo.",
    image: "/images/events/sara-y-blase/foto-9.webp",
  },
  ceremony: {
    name: "Parroquia del Señor del Salitre",
    time: "4:00 p. m.",
    address: "Parroquia del Señor del Salitre",
    mapsUrl: "https://maps.app.goo.gl/z77oQDxjuoguRbeF8?g_st=ic",
    image: "/images/events/sara-y-blase/foto-3.webp",
  },
  reception: {
    name: "Salón Marbella",
    time: "6:00 p. m.",
    address: "Salón Marbella",
    mapsUrl: "https://maps.app.goo.gl/R4kf5fYwY1Dg3tM5A?g_st=ic",
    image: "/images/events/sara-y-blase/foto-10.webp",
  },
  gallery: [
    { src: "/images/events/sara-y-blase/foto-1.webp", alt: "Sara y Blase juntos en el campo" },
    { src: "/images/events/sara-y-blase/foto-2.webp", alt: "Sara y Blase compartiendo un momento especial" },
    { src: "/images/events/sara-y-blase/foto-3.webp", alt: "Sara y Blase abrazados" },
    { src: "/images/events/sara-y-blase/foto-4.webp", alt: "Sara y Blase bajo la luz de los árboles" },
    { src: "/images/events/sara-y-blase/foto-5.webp", alt: "Retrato de Sara y Blase" },
    { src: "/images/events/sara-y-blase/foto-6.webp", alt: "Sara y Blase celebrando su amor" },
    { src: "/images/events/sara-y-blase/foto-7.webp", alt: "Sara y Blase sonriendo juntos" },
    { src: "/images/events/sara-y-blase/foto-8.webp", alt: "Las manos de Sara y Blase" },
    { src: "/images/events/sara-y-blase/foto-9.webp", alt: "Sara y Blase en el paisaje" },
    { src: "/images/events/sara-y-blase/foto-10.webp", alt: "Sara y Blase mirándose con cariño" },
  ],
  contact: {
    phone: "4951010484",
    whatsapp: "https://wa.me/524951010484",
  },
  music: {
    enabled: true,
    url: "/audio/sara-blase-yellow.mp3",
    label: "Yellow · Coldplay",
  },
  itinerary: [
    { time: "16:00", title: "Ceremonia", description: "Parroquia del Señor del Salitre", icon: "heart" },
    { time: "18:00", title: "Recepción", description: "Salón Marbella", icon: "glass" },
  ],
  theme: { primary: "#a9563f", dark: "#432d27", champagne: "#c9a56c", cream: "#f3e2d5", ivory: "#fffaf4", rose: "#cf8066", sage: "#73785e" },
};
