export const selfida60 = {
  slug: "selfida-60",
  templateKey: "selfida-60-red-gold",
  eventTitle: "60 años de Selfida Pérez Córdova",
  couple: { partner1: "Selfida Pérez Córdova", partner2: "60 años" },
  displayNames: { partner1: "Selfida Pérez Córdova", partner2: "" },
  date: "2026-11-22T15:00:00-06:00",
  timezone: "America/Mexico_City",
  maxCompanions: 0,
  rsvpEnabled: false,
  dateStamp: "22 · 11 · 2026",
  dateDisplay: "Domingo · 22 de noviembre · 2026",
  calendarDate: "22 de noviembre de 2026",
  hero: {
    subtitle: "Mis 60 años",
    quote: "La vida está hecha de momentos, recuerdos y personas especiales. Me dará mucha alegría celebrar contigo seis décadas de historias y bendiciones.",
    image: "/images/events/selfidaperez/image.png",
  },
  closingImage: "/images/events/selfidaperez/image.png",
  ceremony: { enabled: false, name: "", time: "", address: "", mapsUrl: "", image: "" },
  reception: {
    enabled: true,
    name: "Celebremos mis 60 años",
    time: "3:00 p. m.",
    address: "Ejido Cuauhtémoc, casa 431",
    mapsUrl: "",
    image: "/images/events/selfidaperez/floral.png",
  },
  gallery: [],
  gifts: [],
  contact: {},
  music: { enabled: true, url: "/audio/selfidaperez.mp3", label: "Mi canción" },
  itinerary: [],
  theme: { primary: "#9f1824", dark: "#4d1118", champagne: "#e0c174", cream: "#fff7e8", ivory: "#fffaf0", rose: "#b72a34", sage: "#536244" },
};
