export const xochitlRuben = {
  slug: "xochitl-y-ruben",
  templateKey: "xochitl-ruben-vintage",
  eventTitle: "Boda de Xóchitl y Rubén",
  couple: { partner1: "Xóchitl", partner2: "Rubén" },
  displayNames: { partner1: "Xóchitl", partner2: "Rubén" },
  date: "2026-12-05T19:00:00-06:00",
  timezone: "America/Monterrey",
  maxCompanions: 0,
  rsvpEnabled: true,
  dateStamp: "05 · 12 · 2026",
  dateDisplay: "Sábado · 5 de diciembre · 2026",
  calendarDate: "5 de diciembre de 2026",
  hero: {
    subtitle: "Nuestra boda",
    quote: "Hay momentos que cambian nuestra historia para siempre. Queremos compartir contigo la alegría de unir nuestras vidas.",
    image: "/images/events/xochitl-y-ruben/recuerdo-1.png",
  },
  closingImage: "/images/events/xochitl-y-ruben/portada.png",
  ceremony: {
    enabled: true,
    name: "Parroquia Cristo Buen Pastor",
    time: "3:00 p. m.",
    address: "Av. de las Arboledas, Fresnos, Apodaca, Nuevo León",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Parroquia+Cristo+Buen+Pastor+Av+de+las+Arboledas+Fresnos+Apodaca+Nuevo+Leon",
    image: "/images/events/xochitl-y-ruben/floral.png",
  },
  reception: {
    enabled: true,
    name: "El Patio Eventos",
    time: "7:00 p. m.",
    address: "Av. República de Chile 304, Col. Las Américas, Apodaca, Nuevo León",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=El+Patio+Eventos+Av+Republica+de+Chile+304+Las+Americas+Apodaca+Nuevo+Leon",
    image: "/images/events/xochitl-y-ruben/floral.png",
  },
  gallery: [
    { src: "/images/events/xochitl-y-ruben/recuerdo-3.png", alt: "Xóchitl y Rubén, un recuerdo juntos", width: 480, height: 779 },
    { src: "/images/events/xochitl-y-ruben/portada.png", alt: "Xóchitl y Rubén celebrando juntos", width: 449, height: 1034 },
  ],
  adultsOnly: {
    title: "Celebración solo para adultos",
    text: "Aunque queremos mucho a los pequeños, esta celebración ha sido planeada únicamente para adultos. Agradecemos de corazón tu comprensión.",
  },
  dressCode: {
    title: "Elegante",
    text: "Agradecemos respetar los colores reservados para los novios.",
  },
  dressGroups: [
    {
      title: "Damas",
      text: "Evitar rojo, azul y colores similares al blanco, reservado para la novia.",
      colors: [
        { name: "Rojo", hex: "#8f1f2b" },
        { name: "Azul", hex: "#23436a" },
        { name: "Blanco", hex: "#f7f3ea" },
      ],
    },
    {
      title: "Caballeros",
      text: "Evitar el negro, color reservado para el novio.",
      colors: [{ name: "Negro", hex: "#191715" }],
    },
  ],
  gifts: [{
    name: "Lluvia de sobres",
    description: "Si deseas hacernos un detalle, con mucho cariño recibiremos tu obsequio mediante lluvia de sobres.",
    type: "cash",
  }],
  bank: { enabled: false, bank: "", holder: "", account: "", clabe: "" },
  contact: { phone: "", whatsapp: "" },
  music: { enabled: true, url: "/audio/XochitlRuben.mp3", label: "Nuestra canción" },
  itinerary: [],
  theme: {
    primary: "#6b4a32",
    dark: "#2b1c14",
    champagne: "#c39a5b",
    cream: "#e8d4b4",
    ivory: "#fbf5ea",
  },
};
